### PR TITLE
Add travis ci support for the project

### PR DESCRIPTION
**Pull request by zeroual**
configure continuous integration  platform  to test and build the application

### CODE REVIEW

**Comment by vdemeester** [comment]
All right I'm okay with the simplest thing for now 👼. When/If we want to tests against multiple docker host version, we'll update the CI configuration/scripts.

Let's wait for it to be activate on the repos and ran for this PR before merging :stuck_out_tongue_closed_eyes:.
/cc @FaustXVI 👼

**Comment by zeroual** [comment]
@FaustXVI  you have to configure this repo to not be ready to merge in master if CI checks failed

**Comment by FaustXVI** [comment]
We will need docker to be available. Check https://docs.travis-ci.com/user/docker/

**Comment by zeroual** [comment]
okay

**Comment by vdemeester** [comment]
@FaustXVI test failures 👼
You need to set a lower api version in tests too 😝

**Comment by zeroual** [comment]
hum , we will fix that tomorrow  😄

**Comment by vdemeester** [comment]
@FaustXVI you need to fix your tests :angel: (when nginx or other images are not present, it should pull them :stuck_out_tongue_closed_eyes: — which does not seems the same for now)

**Comment by FaustXVI** [comment]
Fixed on my branche :p
I will push soon

Xavier Detant

**Comment by vdemeester** [comment]
@FaustXVI cool !
@zeroual remove your last commit then :wink:

**Comment by zeroual** [comment]
@FaustXVI  i rebased with maser :)

**Pull request merged**
