### PR TITLE
[WIP] extracting version of plugins and dependencies

### PR DESCRIPTION
**Pull request by ksouf**
extracting versions of plugins dependencies into properties in order to facilitate the maintenance

### CODE REVIEW

**Comment by FaustXVI** [comment]
Is this PR still WIP ?
So far, I fail to understand how it make dependencies management easier. Could you explain please ?

**Comment by zeroual** [comment]
I think that easy to know which version  we use for each dependency if they are in same section.
In this way tomorrow if we want to change a version we know where to change it

**Comment by FaustXVI** [comment]
This PR is not up-to-date and idle since a long time :/ should I close it ?

**Comment by vdemeester** [comment]
💥

**Pull request closed without merging**
